### ISSUE TITLE
Additional methods for changing button text color and next arrow?

### ISSUE THREAD

**Issue by anta40** [Swisyn/Android-Onboarder#2]
Hi,

I just tested this library to implement an intro. Very easy to use, and so far no issue with Kotlin .
Here's my [test app](https://github.com/anta40/BandIntroApp).

I noticed 2 possible improvements, though. Please take a look at this screenshot:
![bia](https://user-images.githubusercontent.com/16976/40631369-386c8e06-6306-11e8-8d6f-7c036fa32fff.png)

1. Seems that by default, the text color of both Skip and Done buttons is white, and because the background color of the Intro activity is also white, thus it's nearly impossible to see those buttons.
It would be nice to have, say `setSkipButtonTitleColor(Color.RED)`, for example.

2. Is it possible to replace the "next arrow" ( **>** ) with something, say with the text "Next" or "More"?

**Comment by Swisyn** [comment]
Hey,

thank you for using this library. 

I've added several methods that can help you with more customization.

version 1.0.2 will be available within 1 or 2 hours.

`setFinishButtonTextColor(@ColorRes int color)`
`setNextButtonTextColor(@ColorRes int color)`
`setSkipButtonTextColor(@ColorRes int color)`
`setFinishButtonBackgroundColor(@ColorRes int color)`
`setSkipButtonBackgroundColor(@ColorRes int color) `
`setNextButtonBackgroundColor(@ColorRes int color)`
`setNextButtonTitle(CharSequence title)`
`setNextButtonTitle(@StringRes int titleResId)`
`setNextButtonIcon(@DrawableRes int drawableResId)`
