### ISSUE TITLE
setNextButtonTextColor() does not work

### ISSUE THREAD

**Issue by owususamuel** [Swisyn/Android-Onboarder#4]
the function above is not working for me. please check it

**Comment by Swisyn** [comment]
i've fixed the issue, please update library's version to 1.0.3

**Comment by owususamuel** [comment]
Got  ' error: failed linking references.' when I updated to the new version. It compiled successfully when I reversed back the version to 1.0.2.
Kindly check that for me

**Comment by Swisyn** [comment]
> Got ' error: failed linking references.' when I updated to the new version. It compiled successfully when I reversed back the version to 1.0.2.
> Kindly check that for me

Would you please give more details about the issue? I've tested 1.0.2 on a fresh new project with no issues.
